version: "3.8"
services:
    mysql-service:
      image: mysql:8.0.27
      restart: always
      ports:
        - "3306:3306"
      expose: [ 3306 ]
      volumes:
        - ./database_sql:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=ThePassword
        - MYSQL_DATABASE=db_trabalho1